//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int urunID { get; set; }

        [Required(ErrorMessage ="Bu alan boþ geçilemez.")]
        public string urunAd { get; set; }

        [Required(ErrorMessage ="Bu alan boþ geçilemez.")]
        public string urunMarka { get; set; }

       
        public Nullable<short> urunKategori { get; set; }

        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        public Nullable<decimal> urunFiyat { get; set; }

        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        public Nullable<byte> urunStok { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
